return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"bash",
				"gitignore",
				"diff",
				"printf",
				"lua",
				"luadoc",
				"luap",
				"markdown",
				"markdown_inline",
				"python",
				"requirements",
				"regex",
				"sql",
				"query",
				"vim",
				"vimdoc",
				"toml",
				"yaml",
				"xml",
				"json",
				"jsonc",
				"json5",
				"html",
				"javascript",
				"jsdoc",
				"typescript",
				"tsx",
				"dockerfile",
				"rust",
				"hcl",
				"terraform",
				"helm",
				"go",
				"gomod",
				"zig",
			},
			sync_install = false,
			auto_install = true,
			highlight = {
				enable = true,
				additional_vim_regex_highlighting = false,
			},
			indent = {
				enable = true,
			},
		})
	end,
}
