[tools]
node = "latest"
go = "latest"
zig = "latest"
golangci-lint = "latest"
terraform = "latest"
nub = { version = "latest", allow_builds = ["@nubjs/nub"] }
uv = "latest"
gh = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = "create|source"
dotfiles.root = "~/.dotfiles"

[bootstrap.services.mise-history]
builtin = "history-watch"

[history.origin]
url = "https://github.com/rickyhugo/mise-setup.git"
branch = "main"

[dotfiles]
"~/.config/mise/config.toml" = { source = "~/dotfiles/mise/config.toml", mode = "symlink" }
"~/.config/nvim" = { source = "~/dotfiles/nvim", mode = "symlink" }

# "~/.config/mise/config.toml" = { mode = "track", variants = [
#   { os = "linux", profile = "personal" },
# ] }
"~/.gitconfig" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/.global.gitignore" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/.global.taplo.toml" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/.tmux.conf" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/.zprofile" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/.zshrc" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
"~/global.gitignore" = { mode = "track", variants = [
  { os = "linux", profile = "personal" },
] }
