k9s:
  cluster: gke_anyfin_europe-west1_anykube
  namespace:
    active: default
    lockFavorites: false
    favorites:
      - default
  view:
    active: v1/pods default
  featureGates:
    nodeShell: false
  proxy: null
