[tool.ruff]
indent-width = 4
line-length = 80

[tool.ruff.lint]
select = ["ALL"]
fixable = ["ALL"]
ignore = [
    "COM812", # INFO: disable `missing-trailing-comma` when used in conjunction with `skip-magic-trailing-comma = true`
    "CPY001", # INFO: disable `missing-copyright-notice`
    "ISC001", # INFO: disable `single-line-implicit-string-concatenation`
]
isort = { split-on-trailing-comma = false }
preview = true
pydocstyle = { convention = "numpy" }

[tool.ruff.lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "D",    # INFO: don't enforce docstrings in tests
    "S101", # INFO: allow `assert` in tests
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 80
indent-style = "space"
line-ending = "auto"
preview = true
quote-style = "double"
skip-magic-trailing-comma = true

[tool.basedpyright]
typeCheckingMode = "all"

[tool.pyright]
typeCheckingMode = "strict"

[tool.mypy]
plugins = ["pydantic.mypy"]
check_untyped_defs = true
disallow_untyped_defs = true
follow_imports = "silent"
ignore_missing_imports = true
pretty = true
show_column_numbers = true
show_error_context = true
warn_redundant_casts = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[tool.sqlfluff.core]
dialect = "snowflake"
exclude_rules = ["ambiguous.column_count"]
max_line_length = 80
templater = "jinja"
