[tools]
node = "22"
python = "latest"
go = "latest"
ruby = "latest"
java = "21"
zig = "0.13"
uv = "latest"

[env]
GH_CONFIG_DIR = "/home/huen/.config/gh/personal"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
